"""
Behavior Detection Module for Mechanistic Interpretability.
Pre-registered rule-based evaluation of model generations against target behaviors.
"""

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger(__name__)


def load_detector_config(config_path: Union[str, Path] = "config/detector.json") -> Dict[str, Any]:
    """
    Load pre-registered behavior detection configuration from JSON.

    Args:
        config_path: Path to the detector configuration JSON file.

    Returns:
        Dict containing detection rules and configuration metadata.
    """
    path = Path(config_path)
    if not path.exists():
        raise FileNotFoundError(f"Detector configuration not found at {path.resolve()}")

    with open(path, "r", encoding="utf-8") as f:
        config = json.load(f)

    if not isinstance(config, dict):
        raise ValueError(f"Detector config must be a JSON object, got {type(config)}")

    # Normalize rules / regex_patterns
    if "rules" not in config and "regex_patterns" in config:
        config["rules"] = config["regex_patterns"]
    elif "rules" not in config:
        config["rules"] = []

    return config


def detect_behavior(generation: str, config: Optional[Dict[str, Any]] = None) -> bool:
    """
    Evaluates whether a generated string exhibits the target behavior based on pre-registered rules.

    Args:
        generation: The text generated by the model.
        config: Pre-registered rules dictionary (e.g. regex patterns). If None, loads config/detector.json.

    Returns:
        bool indicating presence of the target behavior.
    """
    if not generation or not isinstance(generation, str):
        return False

    if config is None:
        try:
            config = load_detector_config()
        except Exception as e:
            logger.warning(f"Failed to auto-load config/detector.json: {e}")
            return False

    # Extract rules from config
    rules: List[str] = config.get("rules", [])
    if not rules and "regex_patterns" in config:
        rules = config.get("regex_patterns", [])

    for pattern in rules:
        try:
            if re.search(pattern, generation, flags=re.IGNORECASE):
                return True
        except re.error as e:
            logger.error(f"Invalid regex pattern '{pattern}': {e}")

    return False
